TYPE=VIEW
query=select `db_retail`.`tbl_bayar_hutang`.`id_trans` AS `tranid`,`db_retail`.`tbl_bayar_hutang`.`id_hutang` AS `id`,`db_retail`.`tbl_bayar_hutang`.`tran_date` AS `tanggal`,`db_retail`.`tbl_bayar_hutang`.`bukti_bayar` AS `bukti`,`db_retail`.`tbl_bayar_hutang`.`total` AS `total` from `db_retail`.`tbl_bayar_hutang`
md5=a719c7e798b9a826ecbfee03afc2b6fa
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2020-04-19 14:55:04
create-version=1
source=SELECT id_trans as \'tranid\',id_hutang as id, tran_date as \'tanggal\', bukti_bayar as \'bukti\', total FROM tbl_bayar_hutang
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `db_retail`.`tbl_bayar_hutang`.`id_trans` AS `tranid`,`db_retail`.`tbl_bayar_hutang`.`id_hutang` AS `id`,`db_retail`.`tbl_bayar_hutang`.`tran_date` AS `tanggal`,`db_retail`.`tbl_bayar_hutang`.`bukti_bayar` AS `bukti`,`db_retail`.`tbl_bayar_hutang`.`total` AS `total` from `db_retail`.`tbl_bayar_hutang`
