TYPE=VIEW
query=select `a`.`tran_date` AS `TANGGAL`,`a`.`kode_item` AS `KODE_ITEM`,`e`.`sku` AS `SKU`,`e`.`barcode` AS `BARCODE`,`e`.`item_name` AS `NAMA_ITEM`,`f`.`descrip` AS `SAT`,`g`.`id` AS `ID_KATEGORI`,`g`.`kategori` AS `KATEGORI`,`h`.`id` AS `ID_SUPPLIER`,`h`.`nama` AS `SUPPLIER`,`a`.`qty` AS `STOCK_AWAL`,`c`.`qty` AS `PEMBELIAN`,`d`.`qty` AS `PENJUALAN`,`i`.`qty` AS `STOCK_OUT`,`j`.`qty` AS `STOCK_OPNAME`,`b`.`qty` AS `STOCK_AKHIR` from (((((((((`db_retail`.`v_mutasi_stock_awal` `a` join `db_retail`.`v_mutasi_stock_akhir` `b` on(((`b`.`kode_item` = `a`.`kode_item`) and (`b`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`v_mutasi_stock_purchase` `c` on(((`c`.`kode_item` = `a`.`kode_item`) and (`c`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`v_mutasi_stock_sale` `d` on(((`d`.`kode_item` = `a`.`kode_item`) and (`d`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`tbl_item` `e` on((`e`.`item_code` = `a`.`kode_item`))) join `db_retail`.`tbl_satuan` `f` on((`f`.`id` = `e`.`sat`))) join `db_retail`.`tbl_kategori` `g` on((`g`.`id` = `e`.`id_kategori`))) join `db_retail`.`tbl_supplier` `h` on((`h`.`id` = `e`.`id_supplier`))) join `db_retail`.`v_mutasi_stock_out` `i` on(((`i`.`tran_date` = `a`.`tran_date`) and (`i`.`kode_item` = `a`.`kode_item`)))) join `db_retail`.`v_mutasi_stock_opname` `j` on(((`j`.`tran_date` = `a`.`tran_date`) and (`j`.`kode_item` = `a`.`kode_item`)))) order by `a`.`tran_date`
md5=4ce2c0e19d0794ca4f97044901d3f2b5
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-04-06 06:32:48
create-version=1
source=SELECT\na.tran_date AS TANGGAL,\na.kode_item AS KODE_ITEM,\ne.sku AS SKU,\ne.barcode AS BARCODE,\ne.item_name AS NAMA_ITEM,\nf.descrip AS SAT,\ng.id AS ID_KATEGORI,\ng.kategori AS KATEGORI,\nh.id AS ID_SUPPLIER,\nh.nama AS SUPPLIER,\na.qty AS STOCK_AWAL,\nc.qty AS PEMBELIAN,\nd.qty AS PENJUALAN,\ni.qty AS STOCK_OUT,\nj.qty AS STOCK_OPNAME,\nb.qty AS STOCK_AKHIR\nFROM\n((((((((v_mutasi_stock_awal AS a\nJOIN v_mutasi_stock_akhir AS b ON (((b.kode_item = a.kode_item) AND (b.tran_date = a.tran_date))))\nJOIN v_mutasi_stock_purchase AS c ON (((c.kode_item = a.kode_item) AND (c.tran_date = a.tran_date))))\nJOIN v_mutasi_stock_sale AS d ON (((d.kode_item = a.kode_item) AND (d.tran_date = a.tran_date))))\nJOIN tbl_item AS e ON ((e.item_code = a.kode_item)))\nJOIN tbl_satuan AS f ON ((f.id = e.sat)))\nJOIN tbl_kategori AS g ON ((g.id = e.id_kategori)))\nJOIN tbl_supplier AS h ON ((h.id = e.id_supplier)))\nJOIN v_mutasi_stock_out AS i ON (((i.tran_date = a.tran_date) AND (i.kode_item = a.kode_item))))\nINNER JOIN v_mutasi_stock_opname AS j ON j.tran_date = a.tran_date AND j.kode_item = a.kode_item\nORDER BY\nTANGGAL ASC
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `a`.`tran_date` AS `TANGGAL`,`a`.`kode_item` AS `KODE_ITEM`,`e`.`sku` AS `SKU`,`e`.`barcode` AS `BARCODE`,`e`.`item_name` AS `NAMA_ITEM`,`f`.`descrip` AS `SAT`,`g`.`id` AS `ID_KATEGORI`,`g`.`kategori` AS `KATEGORI`,`h`.`id` AS `ID_SUPPLIER`,`h`.`nama` AS `SUPPLIER`,`a`.`qty` AS `STOCK_AWAL`,`c`.`qty` AS `PEMBELIAN`,`d`.`qty` AS `PENJUALAN`,`i`.`qty` AS `STOCK_OUT`,`j`.`qty` AS `STOCK_OPNAME`,`b`.`qty` AS `STOCK_AKHIR` from (((((((((`db_retail`.`v_mutasi_stock_awal` `a` join `db_retail`.`v_mutasi_stock_akhir` `b` on(((`b`.`kode_item` = `a`.`kode_item`) and (`b`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`v_mutasi_stock_purchase` `c` on(((`c`.`kode_item` = `a`.`kode_item`) and (`c`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`v_mutasi_stock_sale` `d` on(((`d`.`kode_item` = `a`.`kode_item`) and (`d`.`tran_date` = `a`.`tran_date`)))) join `db_retail`.`tbl_item` `e` on((`e`.`item_code` = `a`.`kode_item`))) join `db_retail`.`tbl_satuan` `f` on((`f`.`id` = `e`.`sat`))) join `db_retail`.`tbl_kategori` `g` on((`g`.`id` = `e`.`id_kategori`))) join `db_retail`.`tbl_supplier` `h` on((`h`.`id` = `e`.`id_supplier`))) join `db_retail`.`v_mutasi_stock_out` `i` on(((`i`.`tran_date` = `a`.`tran_date`) and (`i`.`kode_item` = `a`.`kode_item`)))) join `db_retail`.`v_mutasi_stock_opname` `j` on(((`j`.`tran_date` = `a`.`tran_date`) and (`j`.`kode_item` = `a`.`kode_item`)))) order by `a`.`tran_date`
